version: '3.9'

services:
  server:
    image: yadavkapil9560/queue-cure-server:${IMAGE_TAG:-latest}
    container_name: airbnb-server
    restart: unless-stopped
    env_file:
      - /home/ubuntu/airbnb/.env
    networks:
      - airbnb-prod-network

  client:
    image: yadavkapil9560/queue-cure-client:${IMAGE_TAG:-latest}
    container_name: airbnb-client
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - airbnb-prod-network

networks:
  airbnb-prod-network:
    driver: bridge
