version: '3.9'

name: rentora

services:
  server:
    image: yadavkapil9560/rentora-server:${IMAGE_TAG:-latest}
    container_name: rentora-server
    restart: unless-stopped
    env_file:
      - /home/ubuntu/rentora/.env
    networks:
      - rentora-prod-network

  client:
    image: yadavkapil9560/rentora-client:${IMAGE_TAG:-latest}
    container_name: rentora-client
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - rentora-prod-network

networks:
  rentora-prod-network:
    name: rentora-prod-network
    driver: bridge
